### ISSUE TITLE
error in installing node opencv

### ISSUE THREAD

**Issue by Nishanksingla** [drejkim/face-detection-node-opencv#4]
How did you installed node opencv ?
when i am trying to install node opencv in my laptop it is giving me lots of error, primarily this error
"node-pre-gyp install --fallback-to-build"
Did you get any error during node opencv installation ?

**Comment by estherjk** [comment]
I just attempted a clean install of this project and am also experiencing this issue. I recently updated to El Capitan and am running node 5.0.0 (installed via brew) and npm 3.3.9.

Looks like others are experiencing this, as well... see https://github.com/peterbraden/node-opencv/issues/325. I also noticed that you opened an issue with node-opencv: https://github.com/peterbraden/node-opencv/issues/333.

**Comment by estherjk** [comment]
Ok! I saw this https://github.com/peterbraden/node-opencv/issues/293 just after commenting above. Please try this workaround:
- In `package.json`, remove `"opencv": "3.0.0",` and run `npm install` with the rest of the dependencies
- Then, run `npm install peterbraden/node-opencv`

This should install the latest node-opencv from master, which doesn't have a release label attached to it yet. The package author plans to do that soon. Please let me know if this works for you!

**Comment by Nishanksingla** [comment]
Have you tried this ? Is this working ?
npm install opencv is not working.
Same errors are coming as I mentioned in my open issue  at
peterbraden/node-opencv
https://github.com/peterbraden/node-opencv/issues/293.
Do I have to add opencv in PATH variable in Ubuntu ?
What does pkg-config do ?
Error with node-pre-gyp

**Comment by estherjk** [comment]
Yes, the steps I outlined above worked for me. Please look at the second step: you won't run `npm install opencv`, but `npm install peterbraden/node-opencv`. And also make sure you have OpenCV 2.4.x installed.

**Comment by Nishanksingla** [comment]
I have opencv 3.0.0 installed.
I am getting the same errors again and again.
Here is the error

npm WARN installMany node-pre-gyp was bundled with opencv@3.2.0, but
bundled package wasn't found in unpacked tree

> opencv@3.2.0 install
> /home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv
> _node-pre-gyp install --fallback-to-build_

make: Entering directory
'/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build'
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:0:
../src/CascadeClassifierWrap.h:5:7: error: ‘CascadeClassifier’ in namespace
‘cv’ does not name a type
   cv::CascadeClassifier cc;
       ^
In file included from ../src/init.cc:6:0:
../src/VideoCaptureWrap.h:5:7: error: ‘VideoCapture’ in namespace ‘cv’ does
not name a type
   cv::VideoCapture cap;
       ^
In file included from ../src/init.cc:15:0:
../src/Stereo.h:8:7: error: ‘StereoBM’ in namespace ‘cv’ does not name a
type
   cv::StereoBM stereo;
       ^
../src/Stereo.h:14:29: error: ‘cv::StereoBM’ has not been declared
   StereoBM(int preset = cv::StereoBM::BASIC_PRESET, int ndisparities = 0,
                             ^
../src/Stereo.h:23:7: error: ‘StereoSGBM’ in namespace ‘cv’ does not name a
type
   cv::StereoSGBM stereo;
       ^
opencv.target.mk:111: recipe for target
'Release/obj.target/opencv/src/init.o' failed
make: **\* [Release/obj.target/opencv/src/init.o] Error 1
make: Leaving directory
'/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/usr/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-31-generic
gyp ERR! command "/usr/bin/nodejs"
"/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build"
"--fallback-to-build"
"--module=/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-linux-x64/opencv.node"
"--module_name=opencv"
"--module_path=/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-linux-x64"
gyp ERR! cwd
/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs
/usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build
--module=/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-linux-x64/opencv.node
--module_name=opencv
--module_path=/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-linux-x64'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.19.0-31-generic
node-pre-gyp ERR! command "/usr/bin/nodejs"
"/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/node_modules/.bin/node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.15
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs
/usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build
--module=/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-linux-x64/opencv.node
--module_name=opencv
--module_path=/home/nishank/Downloads/face-detection-node-opencv-master/server/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-linux-x64'
(1)
npm ERR! Linux 3.19.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
"peterbraden/node-opencv"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@3.2.0 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/nishank/Downloads/face-detection-node-opencv-master/server/npm-debug.log

**Comment by estherjk** [comment]
I recommend using OpenCV 2.4.x. If you look at the comments in the issue I linked above, it looks like people experience issues with OpenCV 3.x.

**Comment by xenomuta** [comment]
It was fixed in https://github.com/peterbraden/node-opencv/pull/309

**Comment by Nishanksingla** [comment]
For what version of node and npm ? 

I have node 4.2.2 and npm is 2.14.7
Opencv 3.0.0

**Comment by MarioDiar** [comment]
Nishanksingla, I had the same problem as you in Mac OS X El Capitan, the way I solved the issue: First I followed the instructions here: http://prateekvjoshi.com/2013/10/18/package-opencv-not-found-lets-find-it/  and I also updated my npm to version 3.4.0, Node 4.2.2 and using OpenCV 2.4.

**Comment by Nishanksingla** [comment]
Hey Luis
Can you please tell me the steps you have followed ?
I am so confused right now, I have no idea what to do.
I am trying to install opencv 2.4 but I am getting some errors in
installation

**Comment by MarioDiar** [comment]
Sure, I installed openCV 2.4 with ffmpeg support with brew, if you are in ubuntu http://www.samontab.com/web/2014/06/installing-opencv-2-4-9-in-ubuntu-14-04-lts/ you can find help here.

**Comment by Nishanksingla** [comment]
1. ) Installing opencv, (
   http://www.samontab.com/web/2014/06/installing-opencv-2-4-9-in-ubuntu-14-04-lts/
   )
   2.) set pkg-config path using (
   http://prateekvjoshi.com/2013/10/18/package-opencv-not-found-lets-find-it/)

After this what steps and commands you have followed ?

**Comment by MarioDiar** [comment]
And followed this steps from drejkim:
 In package.json, remove "opencv": "3.0.0", and run npm install with the rest of the dependencies
Then, run npm install peterbraden/node-opencv

**Comment by Nishanksingla** [comment]
Ok
Thanks
will try.

**Comment by samartioli** [comment]
So it sounds like this will not work with opencv 3.0.0?
I am getting the same error:

```
In file included from ../src/init.cc:5:0:
../src/CascadeClassifierWrap.h:5:7: error: 'CascadeClassifier' in namespace 'cv' does not name a type
   cv::CascadeClassifier cc;
```

I created a docker image based off of: https://hub.docker.com/r/siomiz/node-opencv/
but instead of Node latest I am using 4.2.2

So my environment is Debian Jessie, opencv 3.0.0 successfully installed, and then running:

`npm install peterbraden/node-opencv`

Is giving me that error. 

It seems like a lot of people are saying to go to opencv 2.4
Can someone give a definitive answer if this will work with opencv 3.0.0 or not?

Thanks! :)

**Comment by estherjk** [comment]
@samartioli it looks like there's an open pull request to make opencv 3.0.0 work with node-opencv... https://github.com/peterbraden/node-opencv/pull/259, but it hasn't been pulled into master yet. As a result, it looks like there's no official support for opencv 3.0.0 at this time. You can try the modifications that are made in this pull request though, if you want to use opencv 3.0.0.

**Comment by Nishanksingla** [comment]
Hey Luis
I am using ubuntu 15.04
and I am getting errors with ffmpeg.
Can you please tell me which ubuntu version you are using and the version
of ffmpeg installed in your  ubuntu?

**Comment by 3ffon** [comment]
had the same issues you had
I solved it by installing https://www.npmjs.com/package/node-pre-gyp
sudo npm install node-pre-gyp

then retry .

good luck

**Comment by VirenMohindra** [comment]
Created a pull request to fix this issue
Adds more steps but it solves the problem for users who want to test the app quick and easy: https://github.com/drejkim/face-detection-node-opencv/pull/5

**Comment by estherjk** [comment]
Resolved with https://github.com/drejkim/face-detection-node-opencv/commit/c817bb54f94aeed526f39acbc3a51df414fa33d1.

**Comment by dmehrotra** [comment]
I know this is closed, but something that worked for me was removing opencv from my package json, and then installing.  And then npm install opencv --save

**Comment by BeanMc** [comment]
1,you set OPENDIR. match with machine,
2, uninstall npm  npm bcrypt. and install again.
i try and fix them. 

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cc
  Matrix.cc
  OpenCV.cc
  CascadeClassifierWrap.cc
  Contours.cc
  Point.cc
  VideoCaptureWrap.cc
  CamShift.cc
  HighGUI.cc
  FaceRecognizer.cc
  Features2d.cc
  BackgroundSubtractor.cc
  Constants.cc
  Calib3D.cc
  ImgProc.cc
  Stereo.cc
..\src\Constants.cc(5): warning C4005: 'CONST': macro redefinition [C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\opencv.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h(153): note: see previous definition of 'CONST' (compiling source file ..\src\Constants.cc)
  LDAWrap.cc
  win_delay_load_hook.cc
     Creating library C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\Release\opencv.lib and object C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build
  \Release\opencv.exp
  Generating code
  Finished generating code
  opencv.vcxproj -> C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\Release\opencv.node
  opencv.vcxproj -> C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\Release\opencv.pdb (Full PDB)
  Copying C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\Release\/opencv.node to C:/Users/lvhln/Desktop/asyncwithMeteor/node_modules/opencv/build/opencv/v5.0.0/Rel
  ease/node-v46-win32-ia32\opencv.node
          1 file(s) copied.
  nativemat.cc
  win_delay_load_hook.cc
     Creating library C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\Release\test_nativemat.lib and object C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\open
  cv\build\Release\test_nativemat.exp
  Generating code
  Finished generating code
  test_nativemat.vcxproj -> C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\Release\test_nativemat.node
  test_nativemat.vcxproj -> C:\Users\lvhln\Desktop\asyncwithMeteor\node_modules\opencv\build\Release\test_nativemat.pdb (Full PDB)
hello@ C:\Users\lvhln\Desktop\asyncwithMeteor
`-- opencv@5.0.0

**Comment by mukulsoftwap** [comment]
I have got error in windows 10
node version 6.9.1
npm version 3.10.8
opencv : 2.4.13

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp)

C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\mukulsoftwap\AppData\Local\Programs\Python\Python35-32", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node" "--module_name=opencv" "--module_path=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64"
gyp ERR! cwd C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
npm WARN face-detection@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "peterbraden/node-opencv"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mukulsoftwap\Desktop\face-detection-nodejs-master\npm-debug.log

**Comment by markoliverbrawn** [comment]
On Windows, I found that if I first installed globally in Powershell it installed and built. 

npm install opencv -g

This done, I then found that it  could then be installed in the project directory. (Also had already installed windows-build-tools and pkg-config globally too whilst flailing about, but not sure now whether they helped or not now).
